apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:              
    app: user-service 
spec:
  selector:
    app: user-service
  ports:
    - name: rest
      port: 80         
      targetPort: 80
    - name: grpc
      port: 5001      
      targetPort: 5001
  type: ClusterIP      