apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test
    image: alpine
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: certs
      mountPath: "/app/certs"
  volumes:
  - name: certs
    secret:
      secretName: user-tls
