apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: carlosms18/microservicio-usuario:dev
        envFrom:
        - configMapRef:
            name: user-config 
        - secretRef:
            name: user-secrets 
        env:
        - name: DB_PASSWORD  
          valueFrom:
            secretKeyRef:
              name: sql-secrets  
              key: SA_PASSWORD
        ports:
        - containerPort: 80    
        - containerPort: 5001  