apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
      - name: catalog-service
        image: carlosms18/microservicio-catalog:dev
        env:
        - name: DB_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: sql-secrets
              key: SA_PASSWORD
        - name: RabbitMQParameters__username
          valueFrom:
            secretKeyRef:
              name: catalog-secrets
              key: RABBITMQ_USERNAME
        - name: RabbitMQParameters__password
          valueFrom:
            secretKeyRef:
              name: catalog-secrets
              key: RABBITMQ_PASSWORD
        - name: ASPNETCORE_ENVIRONMENT 
          value: "Kubernetes"
        ports:
        - containerPort: 80
        - containerPort: 7205