apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secrets
              key: SA_PASSWORD
        - name: MSSQL_MEMORY_LIMIT_MB
          value: "2048"  
        - name: MSSQL_AGENT_ENABLED
          value: "true"  
        - name: MSSQL_TCP_PORT
          value: "1433"
        resources:
          requests:
            cpu: "1000m"  
            memory: "2Gi"  
          limits:
            cpu: "2000m"  
            memory: "3Gi" 
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: sql-storage
      volumes:
      - name: sql-storage
        persistentVolumeClaim:
          claimName: sql-pvc