kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: netpol-test
networking:
  disableDefaultCNI: true
  podSubnet: "192.168.0.0/16"
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
  - containerPort: 443
    hostPort: 443
  labels:
    ingress-ready: "true"