apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress-monitoring.yaml
- monitoring-namespace.yaml
- servicemonitor-user.yaml
- servicemonitor-catalog.yaml
- servicemonitor-cart.yaml
