apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cart-service-monitor
  namespace: monitoring
  labels:
    app: cart-service
    release: prometheus-stack  
spec:
  selector:
    matchLabels:
      app: cart-service
  namespaceSelector:
    matchNames:
    - dev  
  endpoints:
  - port: rest           
    path: /metrics       
    interval: 30s
    scrapeTimeout: 10s