apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml                   
  - ../../base/apps/user
  - ../../base/apps/catalog
  - ../../base/apps/cart
  - ../../base/infrastructure/database
  - ../../base/infrastructure/messaging
  - ../../base/infrastructure/ingress
  - ../../base/network-policies
namespace: dev
images:
  - name: carlosms18/microservicio-usuario:latest
    newName: carlosms18/microservicio-usuario
  - name: carlosms18/microservicio-catalog:latest
    newName: carlosms18/microservicio-catalog
  - name: carlosms18/microservicio-cart:latest
    newName: carlosms18/microservicio-cart
patches:
  - path: apps/patches/environment.yaml
    target:
      kind: Deployment
      name: cart-service
  - path: apps/patches/environment.yaml
    target:
      kind: Deployment
      name: catalog-service
  - path: apps/patches/environment.yaml
    target:
      kind: Deployment
      name: user-service
patchesJson6902:
  - path: infrastructure/patches/ingress-auth-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ecommerce-private-ingress
  - path: apps/patches/ingress-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ecommerce-public-ingress
  - path: apps/patches/ingress-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ecommerce-private-ingress
  - path: apps/patches/ingress-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: health-checks-ingress