 
- op: add
  path: /spec/rules/0/host
  value: 128.203.215.1.sslip.io
- op: add
  path: /metadata/annotations/cert-manager.io~1cluster-issuer
  value: letsencrypt-prod
- op: add
  path: /metadata/annotations/nginx.ingress.kubernetes.io~1ssl-redirect
  value: "true"
- op: add
  path: /spec/tls
  value:
  - hosts:
    - 128.203.215.1.sslip.io
    secretName: ecommerce-public-tls-cert