apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: user-service-policy-temp
spec:
  podSelector:
    matchLabels:
      app: user-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {} 
  egress:
  - {} 
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: catalog-service-policy-temp
spec:
  podSelector:
    matchLabels:
      app: catalog-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {} 
  egress:
  - {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cart-service-policy-temp
spec:
  podSelector:
    matchLabels:
      app: cart-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {} 
  egress:
  - {} 