apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/infrastructure/namespaces
  - ../../../base/apps/user
  - ../../../base/apps/catalog
  - ../../../base/apps/cart
  - ../../../base/infrastructure/database
  - ../../../base/infrastructure/messaging
  - ../../../base/infrastructure/ingress
  - ../../../base/network-policies

namespace: dev
images:
  - name: carlosms18/microservicio-usuario:latest
    newName: carlosms18/microservicio-usuario
    newTag: dev
  - name: carlosms18/microservicio-catalog:latest
    newName: carlosms18/microservicio-catalog
    newTag: dev
  - name: carlosms18/microservicio-cart:latest
    newName: carlosms18/microservicio-cart
    newTag: dev




  