apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: carlosms18/microservicio-cart:dev
        imagePullPolicy: Always
        env:
        - name: DB_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: sql-secrets
              key: SA_PASSWORD
        - name: RabbitMQParameters__username
          valueFrom:
            secretKeyRef:
              name: cart-secrets
              key: RABBITMQ_USERNAME
        - name: RabbitMQParameters__password
          valueFrom:
            secretKeyRef:
              name: cart-secrets
              key: RABBITMQ_PASSWORD
        - name: ASPNETCORE_ENVIRONMENT 
          value: "Kubernetes"
        ports:
        - containerPort: 80
        - containerPort: 7206