apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: dev
spec:
  selector:
    app: catalog-service
  ports:
    - name: rest
      port: 80          
      targetPort: 80    
    - name: grpc
      port: 7205      
      targetPort: 7205
  type: ClusterIP