apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-dev
  template:
    metadata:
      labels:
        app: user-service-dev
    spec:
      containers:
      - name: user-service
        image: carlosms18/microservicio-usuario:dev
        ports:
        - containerPort: 7251  # Puerto REST
        - containerPort: 5003  # Puerto gRPC
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        # ¡Eliminado! Ya está en tu appsettings.Development.json