apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user-container
        image: carlosms18/microservicio-usuario:1.0.6
        ports:
        - containerPort: 5003  # gRPC
        - containerPort: 7251  # REST
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "/app/certs/tls.pfx"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          value: ""
        volumeMounts:
        - name: certs
          mountPath: "/app/certs"
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: user-tls
          items:
          - key: tls.pfx
            path: tls.pfx
          defaultMode: 0444