apiVersion: v1
kind: Service
metadata:
  name: user-service-dev
spec:
  type: ClusterIP   # Para acceso externo en desarrollo
  selector:
    app: user-service-dev
  ports:
    - name: rest
      port: 80
      targetPort: 7251
      nodePort: 30080  # Puerto fijo para REST
    - name: grpc
      port: 5003
      targetPort: 5003
      nodePort: 30503  # Puerto fijo para gRPC