apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
  - name: grpc
    port: 5003
    targetPort: 5003
  - name: http
    port: 80
    targetPort: 7251