apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: dev
spec:
  selector:
    app: cart-service
  ports:
    - name: rest
      port: 80         
      targetPort: 80
    - name: grpc
      port: 7206      
      targetPort: 7206
  type: ClusterIP