apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service-dev
  template:
    metadata:
      labels:
        app: catalog-service-dev
    spec:
      containers:
      - name: catalog-service
        image: carlosms18/microservicio-catalog:dev
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development