apiVersion: v1
kind: Service
metadata:
  name: catalog-service-dev
spec:
  type: ClusterIP 
  selector:
    app: catalog-service
    environment: dev
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30081 # Diferente al de user-service (30080)