name: Catalog CI
on:
  push:
    branches: [ main ]
    paths: [ 'src/Catalog/**', 'tests/Catalog/**' ]
jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: P@ssw0rd123!
        ports:
          - 1433:1433
    env:
      CI: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'
        
    - name: Run Unit Tests
      run: dotnet test tests/Catalog/Catalog.UnitTests/ --configuration Release --verbosity normal
      
    - name: Run Integration Tests
      run: dotnet test tests/Catalog/Catalog.IntegrationTests/ --configuration Release --verbosity normal