name: Production Deploy
on:
  workflow_dispatch:
  push:
    branches: [ deploy-production ]
    paths: [ '.github/workflows/deploy-production.yml' ]

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Just a test
        run: |
          echo "Production Deploy workflow is now visible!"
          echo "This is just a test run to make it appear in GitHub Actions"
          echo "No actual deployment happening here"