name: Production Deploy

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "DEPLOY" to confirm production deployment'
        required: true
        default: ''

env:
  DOTNET_VERSION: '7.0.x'
  AZURE_CONTAINER_REGISTRY: 'microservicioscarlos'

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Confirm Deployment
        run: |
          if [ "${{ github.event.inputs.confirmation }}" != "DEPLOY" ]; then
            echo "Deployment cancelled. You must type 'DEPLOY' to confirm."
            exit 1
          fi
          echo "Production deployment confirmed!"
          
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Login to ACR
        run: |
          az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}
          
      - name: Build and Push Images to ACR
        run: |
          echo "Building images with latest tag"
          ACR_URL="${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io"
          TAG="prod-$(date +%Y%m%d-%H%M%S)"  
          
          echo "Using production tag: $TAG"
   
          echo "Building Cart service..."
          dotnet publish src/Cart/Cart.WebAPI/Cart.WebAPI.csproj -c Release -o src/Cart/Cart.WebAPI/publish
          docker build -t $ACR_URL/microservicio-cart:$TAG -f src/Cart/Cart.WebAPI/Dockerfile .
          docker push $ACR_URL/microservicio-cart:$TAG
          
          echo "Building Catalog service..."
          dotnet publish src/Catalog/Catalog.WebApi/Catalog.WebAPI.csproj -c Release -o src/Catalog/publish
          docker build -t $ACR_URL/microservicio-catalog:$TAG -f src/Catalog/Catalog.WebApi/Dockerfile .
          docker push $ACR_URL/microservicio-catalog:$TAG
          
          echo "Building User service..."
          dotnet publish src/User/User.WebAPI/User.WebAPI.csproj -c Release -o src/User/publish
          docker build -t $ACR_URL/microservicio-usuario:$TAG -f src/User/User.WebAPI/Dockerfile .
          docker push $ACR_URL/microservicio-usuario:$TAG
          
          echo "All images built and pushed to ACR with tag: $TAG"
          
          echo "PROD_TAG=$TAG" >> $GITHUB_ENV
          
      - name: Update Production Manifests GitOps
        run: |
          echo "Updating production manifests with new tag: $PROD_TAG"
          
          sed -i "s|newTag: .*|newTag: $PROD_TAG|g" k8s/overlays/production/kustomization.yaml
          
          echo "Updated kustomization.yaml content:"
          cat k8s/overlays/production/kustomization.yaml
          
      - name: Create Pull Request for Production Update
        run: |
          BRANCH_NAME="production-deploy-$PROD_TAG"
          
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action - Production Deploy"
          
          git checkout -b $BRANCH_NAME
          
          git add k8s/overlays/production/kustomization.yaml
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Production deploy: Update images to $PROD_TAG"
            git push origin $BRANCH_NAME
            
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/pulls \
              -d "{
                \"title\": \"Production Deploy: $PROD_TAG\",
                \"body\": \"Auto-generated Production Deployment\\n\\nDeployment Tag: $PROD_TAG\\nSource Commit: ${{ github.sha }}\\nTriggered by: ${{ github.actor }}\\n\\nImages updated to production tag: $PROD_TAG\",
                \"head\": \"$BRANCH_NAME\",
                \"base\": \"main\"
              }"
              
            echo "Pull Request created successfully!"
            echo "Check GitHub to review, approve and merge the PR"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Deployment Summary
        run: |
          echo "Production deployment process completed!"
          echo ""
          echo "Summary:"
          echo "  - Images built and pushed to ACR with tag: $PROD_TAG"
          echo "  - Pull Request created for production manifests update"
          echo "  - Waiting for PR approval and merge"
          echo ""
          echo "Next steps:"
          echo "  1. Review the auto-created Pull Request in GitHub"
          echo "  2. Approve and merge the PR"
          echo "  3. ArgoCD will automatically sync changes to AKS cluster"
          echo "  4. Monitor ArgoCD UI for deployment progress"
          echo "  5. Check deployment: kubectl get pods -n prod"
          echo ""
          echo "ArgoCD sync typically takes 1-3 minutes after PR merge"