name: Development CI/CD

on:
  push:
    branches: [ main, implementacion-cert-ssl ]
    paths-ignore:
      - 'k8s/overlays/production/**'
      - '*.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/heads/production-deploy-')"
    outputs:
      cart: ${{ steps.changes.outputs.cart }}
      catalog: ${{ steps.changes.outputs.catalog }}
      user: ${{ steps.changes.outputs.user }}
      manifests: ${{ steps.changes.outputs.manifests }}
      source-code: ${{ steps.changes.outputs.source-code }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            cart:
              - 'src/Cart/**'
              - 'tests/Cart/**'
              - 'k8s/base/apps/cart/**'
            catalog:
              - 'src/Catalog/**'
              - 'tests/Catalog/**'
              - 'k8s/base/apps/catalog/**'
            user:
              - 'src/User/**'
              - 'tests/User/**'
              - 'k8s/base/apps/user/**'
            manifests:
              - 'k8s/**'
            source-code:
              - 'src/**'
              - 'tests/**'

  validate-manifests:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: needs.detect-changes.outputs.manifests == 'true' && !startsWith(github.ref, 'refs/heads/production-deploy-')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'
        
      - name: Validate Development Manifests
        run: |
          echo "Validating development manifests..."
          kubectl apply --dry-run=client -k k8s/overlays/development/ --validate=true
          echo "Development manifests are valid!"
          
      - name: Validate Production Manifests  
        run: |
          echo "Validating production manifests..."
          kubectl apply --dry-run=client -k k8s/overlays/production/ --validate=true
          echo "Production manifests are valid!"
          
      - name: Validate Base Manifests
        run: |
          echo "Validating base manifests..."
          find k8s/base -name "*.yaml" -exec kubectl apply --dry-run=client --validate=true -f {} \;
          echo "Base manifests are valid!"
          
      - name: Check Resource Limits
        run: |
          echo "Checking resource limits are defined..."
          if ! grep -r "resources:" k8s/base/apps/*/deployment.yaml; then
            echo "WARNING: Some deployments may be missing resource limits"
          else
            echo "Resource limits found in deployments"
          fi
          
      - name: Security Validation
        run: |
          echo "Security validation..."
          
          echo "Checking for privileged containers..."
          if grep -r "privileged: true" k8s/; then
            echo "ERROR: Privileged containers found!"
            exit 1
          fi
          
          echo "Checking for containers running as root..."
          if grep -rL "runAsNonRoot: true" k8s/base/apps/*/deployment.yaml; then
            echo "WARNING: Some containers may run as root"
          fi
          
          echo "Checking for hostNetwork usage..."
          if grep -r "hostNetwork: true" k8s/; then
            echo "ERROR: hostNetwork usage found!"
            exit 1
          fi
          
          echo "Security validation passed!"

  ci-tests:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: needs.detect-changes.outputs.source-code == 'true' && (needs.detect-changes.outputs.cart == 'true' || needs.detect-changes.outputs.catalog == 'true' || needs.detect-changes.outputs.user == 'true') && !startsWith(github.ref, 'refs/heads/production-deploy-')
    
    strategy:
      matrix:
        service: [cart, catalog, user]
        
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: P@ssw0rd123!
        ports:
          - 1433:1433
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
          
      - name: Run Unit Tests
        if: needs.detect-changes.outputs[matrix.service] == 'true'
        run: dotnet test tests/${{ matrix.service == 'cart' && 'Cart' || matrix.service == 'catalog' && 'Catalog' || 'User' }}/${{ matrix.service == 'cart' && 'Cart' || matrix.service == 'catalog' && 'Catalog' || 'User' }}.UnitTests/ --configuration Release --verbosity normal
        
      - name: Run Integration Tests
        if: needs.detect-changes.outputs[matrix.service] == 'true'
        run: dotnet test tests/${{ matrix.service == 'cart' && 'Cart' || matrix.service == 'catalog' && 'Catalog' || 'User' }}/${{ matrix.service == 'cart' && 'Cart' || matrix.service == 'catalog' && 'Catalog' || 'User' }}.IntegrationTests/ --configuration Release --verbosity normal

  cd-deploy:
    needs: [detect-changes, ci-tests, validate-manifests]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: always() && (needs.ci-tests.result == 'success' || needs.ci-tests.result == 'skipped') && (needs.validate-manifests.result == 'success' || needs.validate-manifests.result == 'skipped') && (needs.detect-changes.outputs.cart == 'true' || needs.detect-changes.outputs.catalog == 'true' || needs.detect-changes.outputs.user == 'true') && !startsWith(github.ref, 'refs/heads/production-deploy-')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and Push Images to Docker Hub
        run: |
          TAG=${GITHUB_SHA:0:7}
          echo "Using tag: $TAG for Docker Hub push"
          
          echo "Building and pushing Cart service..."
          dotnet publish src/Cart/Cart.WebAPI/Cart.WebAPI.csproj -c Release -o src/Cart/Cart.WebAPI/publish
          docker build -t carlosms18/microservicio-cart:$TAG -f src/Cart/Cart.WebAPI/Dockerfile .
          docker push carlosms18/microservicio-cart:$TAG
          
          echo "Building and pushing Catalog service..."
          dotnet publish src/Catalog/Catalog.WebApi/Catalog.WebAPI.csproj -c Release -o src/Catalog/publish
          docker build -t carlosms18/microservicio-catalog:$TAG -f src/Catalog/Catalog.WebApi/Dockerfile .
          docker push carlosms18/microservicio-catalog:$TAG
          
          echo "Building and pushing User service..."
          dotnet publish src/User/User.WebAPI/User.WebAPI.csproj -c Release -o src/User/publish
          docker build -t carlosms18/microservicio-usuario:$TAG -f src/User/User.WebAPI/Dockerfile .
          docker push carlosms18/microservicio-usuario:$TAG
          
          echo "All images built and pushed to Docker Hub with tag: $TAG"
          
      - name: Update Kustomization with New Tags
        run: |
          TAG=${GITHUB_SHA:0:7}
          echo "Updating kustomization.yaml with tag: $TAG"
          
          sed -i "s|newTag: .*|newTag: $TAG|g" k8s/overlays/development/kustomization.yaml
          
          echo "Updated kustomization.yaml content:"
          cat k8s/overlays/development/kustomization.yaml

      - name: Create Kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: netpol-test
          config: infra/kind/kind-config.yaml
          
      - name: Wait for cluster to be ready
        run: |
          kubectl cluster-info
          kubectl get nodes
          
      - name: Create local storage class
        run: |
          kubectl apply -f - <<EOF
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: local-storage
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
          provisioner: rancher.io/local-path
          volumeBindingMode: WaitForFirstConsumer
          reclaimPolicy: Delete
          EOF
          
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
         version: 'v1.28.0' 
        
      - name: Install Calico CNI (for Network Policies)
        run: |
          kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml
          kubectl wait --for=condition=Ready pods --all -n kube-system --timeout=300s
          
      - name: Install NGINX Ingress Controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
          kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=300s
          
      - name: Setup Helm
        uses: azure/setup-helm@v3
        
      - name: Install Prometheus Stack
        run: |
          echo "Adding Prometheus Helm repository..."
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          
          echo "Installing Prometheus Stack..."
          helm install prometheus-stack prometheus-community/kube-prometheus-stack \
            --namespace monitoring \
            --create-namespace \
            --set prometheus.service.type=NodePort \
            --set grafana.service.type=NodePort \
            --wait --timeout=10m
          
          echo "Prometheus Stack installed successfully!"
          
      - name: Build Local Images for Kind
        run: |
          TAG=${GITHUB_SHA:0:7}
          echo "Building local images for Kind with tag: $TAG"
          
          echo "Building Cart service for Kind..."
          docker build -t cart-service:$TAG -f src/Cart/Cart.WebAPI/Dockerfile .
          kind load docker-image cart-service:$TAG --name netpol-test
          
          echo "Building Catalog service for Kind..."
          docker build -t catalog-service:$TAG -f src/Catalog/Catalog.WebApi/Dockerfile .
          kind load docker-image catalog-service:$TAG --name netpol-test
          
          echo "Building User service for Kind..."
          docker build -t user-service:$TAG -f src/User/User.WebAPI/Dockerfile .
          kind load docker-image user-service:$TAG --name netpol-test
          
          echo "All images built and loaded to Kind successfully with tag: $TAG"
          
      - name: Validate Manifests Before Deploy
        run: |
          echo "Final validation before deployment..."
          kubectl apply --dry-run=client -k k8s/overlays/development/ > /dev/null
          kubectl apply --dry-run=client -k k8s/overlays/development/monitoring/ > /dev/null
          echo "All manifests validated successfully!"
          
      - name: Debug Kustomization Files
        run: |
          echo "=== Checking file structure ==="
          find k8s -name "kustomization.yaml" -type f
          
          echo "=== Apps kustomization content ==="
          cat k8s/overlays/development/kustomization.yaml
          
          echo "=== Monitoring kustomization content ==="
          cat k8s/overlays/development/monitoring/kustomization.yaml
          
          echo "=== Testing kustomize build for apps ==="
          kubectl kustomize k8s/overlays/development/ || echo "Apps kustomization failed"
          
          echo "=== Testing kustomize build for monitoring ==="
          kubectl kustomize k8s/overlays/development/monitoring/ || echo "Monitoring kustomization failed"
       
      - name: Deploy to Development
        run: |
          echo "Deploying applications to development environment..."
          kubectl apply -k k8s/overlays/development/ || echo "Apps deployment failed"
          
          echo "Deploying monitoring to development environment..."
          kubectl apply -k k8s/overlays/development/monitoring/ || echo "Monitoring deployment failed"
          
          echo "Development deployment completed!"
          
      - name: Check Deployment Status
        run: |
          echo "=== Checking namespaces ==="
          kubectl get namespaces
          
          echo "=== Checking dev namespace resources ==="
          kubectl get all -n dev || echo "Dev namespace not found or empty"
          
          echo "=== Checking monitoring namespace resources ==="
          kubectl get all -n monitoring || echo "Monitoring namespace not found or empty"
          
      - name: Wait for Application Services
        run: |
          echo "Waiting for application services to be ready..."
          
          if kubectl get namespace dev > /dev/null 2>&1; then
            echo "Dev namespace found, waiting for pods..."
            kubectl wait --for=condition=ready pod -l app=cart-service -n dev --timeout=300s || echo "Cart service timeout"
            kubectl wait --for=condition=ready pod -l app=catalog-service -n dev --timeout=300s || echo "Catalog service timeout"
            kubectl wait --for=condition=ready pod -l app=user-service -n dev --timeout=300s || echo "User service timeout"
          else
            echo "ERROR: Dev namespace not found!"
            exit 1
          fi
          
      - name: Debug Deployment
        if: failure()
        run: |
          echo "=== Checking namespace ==="
          kubectl get namespace dev || echo "Namespace not found"
          
          echo "=== Checking deployments ==="
          kubectl get deployments -n dev || echo "No deployments found"
          
          echo "=== Checking pods ==="
          kubectl get pods -n dev -o wide || echo "No pods found"
          
          echo "=== Checking events ==="
          kubectl get events -n dev --sort-by=.metadata.creationTimestamp || echo "No events found"
          
          echo "=== Pod logs ==="
          kubectl logs -l app=sql-server -n dev --tail=50 || echo "No SQL logs"
          kubectl logs -l app=rabbitmq-service -n dev --tail=50 || echo "No RabbitMQ logs"
          kubectl logs -l app=cart-service -n dev --tail=50 || echo "No Cart logs"
          kubectl logs -l app=catalog-service -n dev --tail=50 || echo "No Catalog logs"
          kubectl logs -l app=user-service -n dev --tail=50 || echo "No User logs"
          
          echo "=== Describe pods ==="
          kubectl describe pods -n dev || echo "No pods to describe"
          
      - name: Test Deployment
        run: |
          echo "=== Final Status Check ==="
          kubectl get pods -o wide --all-namespaces
          kubectl get svc --all-namespaces
          kubectl get ingress -n dev || echo "No ingress found"
          kubectl get networkpolicies -n dev || echo "No network policies found"
          
          echo "=== Testing Services ==="
          
          if kubectl get namespace dev > /dev/null 2>&1; then
            echo "Testing Cart service..."
            if kubectl get svc cart-service -n dev > /dev/null 2>&1; then
              kubectl port-forward svc/cart-service 8080:80 -n dev &
              CART_PID=$!
              sleep 10
              curl -f http://localhost:8080/health || echo "Cart service not ready"
              kill $CART_PID 2>/dev/null || true
            else
              echo "Cart service not found"
            fi
            
            echo "Testing Catalog service..."
            if kubectl get svc catalog-service -n dev > /dev/null 2>&1; then
              kubectl port-forward svc/catalog-service 8081:80 -n dev &
              CATALOG_PID=$!
              sleep 10
              curl -f http://localhost:8081/health || echo "Catalog service not ready"
              kill $CATALOG_PID 2>/dev/null || true
            else
              echo "Catalog service not found"
            fi
            
            echo "Testing User service..."
            if kubectl get svc user-service -n dev > /dev/null 2>&1; then
              kubectl port-forward svc/user-service 8082:80 -n dev &
              USER_PID=$!
              sleep 10
              curl -f http://localhost:8082/health || echo "User service not ready"
              kill $USER_PID 2>/dev/null || true
            else
              echo "User service not found"
            fi
          else
            echo "ERROR: Dev namespace still not found!"
          fi
          
      - name: Cleanup
        if: always()
        run: |
          kind delete cluster --name netpol-test