name: Test User Migration - SIMPLE

on:
  push:
    branches:
      - rama-test-migration
  workflow_dispatch:

env:
  DOTNET_VERSION: '7.0.x'

jobs:
  test-user-migration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Install EF Tools
        run: |
          dotnet tool install --global dotnet-ef --version 7.0.*
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          
      - name: Test Database Connection
        run: |
          echo " Testing database connection..."
          
     
          cat > test-db.cs << 'EOF'
          using System;
          using System.Data.SqlClient;
          
          try 
          {
              var conn = "Server=tcp:microservices-sql-server.database.windows.net,1433;Initial Catalog=microservices-db;User ID=sqladmin;Password=Admin123!;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";
              using var connection = new SqlConnection(conn);
              connection.Open();
              Console.WriteLine(" CONEXIÓN OK");
              using var cmd = new SqlCommand("SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES", connection);
              var count = cmd.ExecuteScalar();
              Console.WriteLine($"Tablas encontradas: {count}");
          }
          catch(Exception ex)
          {
              Console.WriteLine($" ERROR: {ex.Message}");
              Environment.Exit(1);
          }
          EOF
          
          dotnet script test-db.cs
          
      - name: Build User Service
        run: |
          echo " Building User service..."
          cd src/User/User.WebAPI
          dotnet build --configuration Release
          
      - name: Check Migrations
        run: |
          echo " Checking migrations..."
          cd src/User/User.WebAPI
          
          export ConnectionStrings__DefaultConnection="Server=tcp:microservices-sql-server.database.windows.net,1433;Initial Catalog=microservices-db;User ID=sqladmin;Password=Admin123!;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
          
          echo "Migraciones disponibles:"
          dotnet ef migrations list --no-build || echo "No migrations found"
          
      - name: Apply Migrations
        run: |
          echo " Applying migrations..."
          cd src/User/User.WebAPI
          
          export ConnectionStrings__DefaultConnection="Server=tcp:microservices-sql-server.database.windows.net,1433;Initial Catalog=microservices-db;User ID=sqladmin;Password=Admin123!;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
          
      
          dotnet ef database update --no-build --verbose
          
          echo " MIGRACIONES APLICADAS"
          
      - name: Verify Results
        run: |
          echo "Verificando resultados..."
          cd src/User/User.WebAPI
          
          export ConnectionStrings__DefaultConnection="Server=tcp:microservices-sql-server.database.windows.net,1433;Initial Catalog=microservices-db;User ID=sqladmin;Password=Admin123!;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
          
       
          dotnet ef migrations list --no-build
          
          echo " TEST COMPLETADO"